---
- name: Wheel group exists
  group:
    name: wheel
    state: present 
  
- name: Wheel group is passwordless sudoers 
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
