---

- name: make deploy directory
  file:
    path: /app 
    state: directory
    mode: '0755'

- name: docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: /app/docker-compose.yml

# - name: docker-compose up
#   community.general.docker_compose:
#     project_src: /app

